- .github/workflows/main.yml
uses a [slack webhook](https://viaminc.slack.com/apps/A0F7XDUAZ-incoming-webhooks?tab=settings&next_id=0) to send alerts to #team-slam-github-notifs whenever a main branch update fails. 
failing action: https://github.com/viamrobotics/viam-orb-slam3/actions/runs/4407884564
ticket: https://viam.atlassian.net/browse/RSDK-1786
Followup to this PR
https://github.com/viamrobotics/viam-orb-slam3/pull/17
> [RSDK-1786] add slack alerts for failed main branch updates

- Makefile
- internal/testhelper/testhelper.go
Ticket: https://viam.atlassian.net/browse/RSDK-2386
Done:
* Fixed a bug that caused a race condition that was detected when running `go test -race ./...`
> RSDK-2386 - Fix integration test race condition

- internal/testhelper/testhelper.go
- viam-cartographer_test.go
Attempts to fix: https://github.com/viamrobotics/viam-cartographer/actions/runs/4536705514/jobs/7993714034 
Currently, tests are flakey as sometimes the server returns an error. Given that modularization v2 will remove the grpc server, this change doesn't investigate the cause of the error & instead reverts the code back to the pre modularization v1 code state which can still be seen in orbslam here: https://github.com/viamrobotics/viam-orb-slam3/blob/main/viam-orb-slam3_test.go#L77
> revert-setupTestGRPCServer-to-private

- viam-cartographer.go
Remove the unused dev flag in SLAM Map Representation project. Similar edits were also made in rdk, viam-orb-slam3 and slam repo, see associated PRs.
JIRA Ticket: https://viam.atlassian.net/browse/RSDK-2435
Associated PRs: 
- https://github.com/viamrobotics/slam/pull/184
- https://github.com/viamrobotics/rdk/pull/2150
- https://github.com/viamrobotics/viam-orb-slam3/pull/34
> RSDK-2435 Remove Dev Flag Cartographer

- .github/workflows/appimage.yml
currently when a PR gets pushed to main, both the main branch update workflow and the appimage workflow will both run, causing the appimage to be built twice. This PR changes the appimage workflow to [match rdk](https://github.com/viamrobotics/rdk/blob/main/.github/workflows/appimage.yml#L3-L9)
ticket: https://viam.atlassian.net/browse/RSDK-2511
> [RSDK-2511] remove duplicate appimage workflow call

- viam-cartographer/scripts/setup_cartographer_macos.sh
When I tried to build cartographer on my Mac for the first time, I ran into issues with OpenSSL (sadly I don't remember what the error was and didn't save it). @nicksanford and I cross-referenced the `setup_cartographer_macos` script with the `setup_orbslam_macos` script and observed that in orb slam, we run `brew link openssl` with the `--force` flag. When I ran this locally, I stopped getting errors. This PR changes the `setup_cartographer_macos` script to run the correct command.
> [RSDK-2760] Setup script should force install openssl

- Makefile
- etc/packaging/appimages/cartographer-module-aarch64.yml
- etc/packaging/appimages/cartographer-module-x86_64.yml
- etc/packaging/appimages/package_release_module.sh
- viam-cartographer.go
Ticket: https://viam.atlassian.net/browse/RSDK-2021
Done:
* Adds orbslam3-module app image creation to Makefile & github workflow
Tested on:
> RSDK-2021 - Add the cartographer AppImage

- .github/workflows/appimage.yml
- .github/workflows/test.yml
Ticket: https://viam.atlassian.net/browse/RSDK-2029
Done:
* Removed/replaced any RDK builtin based integration tests with viam-cartographer equivalent integration tests
NOTE: 
* Must be merged before merging https://github.com/viamrobotics/rdk/pull/2262
> RSDK-2029 - Remove/replace rdk integration tests with local tests

- Makefile
This PR adds copying the cartographer-module to `/usr/local/bin `when running `make install`.
This was tested by removing the associated binaries, running make install, and seeing them getting copied into  /usr/local/bin with no error.
> Update make install

- viam-cartographer/src/io/file_handler.cc
This PR adds timezone offsets for `ReadTimeFromTimestamp` so that it is platform and timezone-agnostic. The issue is that `mktime` will convert a `struct tm` to LOCAL TIME not UTC.
Note: `timezone` is a global variable in C++ when importing `time.h`: https://www.mkssoftware.com/docs/man5/tzname.5.asp
Tested this on mac with immediate success.
JIRA Ticket: https://viam.atlassian.net/browse/RSDK-2896
> RSDK-2896 Add timezone fix for file handler

- README.md
Ticket: https://viam.atlassian.net/browse/RSDK-2913
Done:
* Changed URLs to start with https://storage.googleapis.com/packages.viam.com/... instead of http://packages.viam.com/...
> RSDK-2913 - Fix AppImage URLs to use https://storage.googleapis.com/packages.viam.com/

- .github/workflows/appimage-comment.yml
- viam-cartographer/src/slam_service/slam_service.cc
noticed the links were still referencing `carto_grpc_server` when adding the appimage label. This is a quick PR to switch it to `cartographer-module`
> [RSDK-2969] update appimage links to use the module

- README.md
I ran into issues with running cartographer today after uninstalling and attempting to reinstall everything. What was missing was running the `make install-lua-files` command, which is why I think we should add it to the set of instructions in the README.
> Fix Readme for seamless setup & build process

- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade.h
- viam-cartographer/src/carto_facade/carto_facade_test.cc
- viam-cartographer/src/main_test.cc
[Ticket](https://viam.atlassian.net/browse/RSDK-3430)
1. Create viam_carto_lib_init & viam_carto_lib_terminate C APIs. init performs any global state setup which is required for the library to function & provides the caller with a struct that can in the future be provided to viam_carto_init initialization as proof that library initialization was performed prior to initialization of a given cartographer instance. terminate leaves the system in the same state it was in before init was called.
2. Convert functions to take a non const `viam_carto` pointer (or pointer to pointer)
3. Converts functions which don't change the viam_carto pointer to only take a pointer with a single level of indirection rather than 2
4. Remove `char **errmsg` from C API. I realized that b/c the carto C API is not …
> [RSDK-3430] viam_carto_lib_init_term

- .github/workflows/appimage.yml
This PR removes redundant testing from appimage workflows.
**Testing:** Tests have been removed and appimage creation still succeeds
https://github.com/viamrobotics/viam-cartographer/actions/runs/5247914392/jobs/9478709060?pr=134
**JIRA ticket:** https://viam.atlassian.net/browse/RSDK-3372
> RSDK-3372 Remove Testing From Appimage Workflow

- .github/workflows/main.yml
- .github/workflows/test.yml
- viam-cartographer.go
This PR is not on a feature branch so that I can use this branch's main.yml definition, as otherwise tests won't pass. 
A follow up PR will be put up after this one is merged which will change main.yml back to what it was before.
Run `sudo apt update` during github workflow before any apt commands are run to ensure stale packages are not being used.
Fixes this error:
https://github.com/viamrobotics/viam-cartographer/actions/runs/5270469128/jobs/9530014193?pr=145
```
sudo apt-get install -y protobuf-compiler-grpc libgrpc-dev libgrpc++-dev || brew install grpc openssl --quiet
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
libabsl20200923 libc-ares2 libgrpc++1 libgrpc10 libprotoc23
The following NEW …
```
> Hotfix run app update fix stale dep

- .github/workflows/appimage.yml
Add sudo apt update step to appimage.yml to ensure cartographer builds properly when using the "appimage-ignore-tests" flag.
> [RSDK-3677] Add apt update to appimage workflow

- Makefile
- viam-cartographer/src/carto_facade/util.cc
Fixes a bug caused by reading invalid memory in mac due to the fact that brew installs PCL on version 1.13.1 & apt installs pcl on version 1.11.1 and there are differences in behavior between the two versions.
[1.11.1](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.11.1/io/src/pcd_io.cpp#L108) readHeader reports an invalid header as an error and [1.13.1 ](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.13.1/io/src/pcd_io.cpp#L108)does not. 
This resulted in our code accessing invalid memory.
This PR also adds a `make build-asan` target which we can use on platforms that support low config asan builds (like osx) during local development (which is how I was able to figure out where the problem was). Full asan support should be added as part of …
> hotfix-fix-mac-sensor-reading-test-failures

- cartofacade/capi.go
- cartofacade/capi_test.go
- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade.h
- viam-cartographer/src/carto_facade/carto_facade_test.cc
- viam-cartographer/src/carto_facade/test_helpers.cc
- viam-cartographer/src/carto_facade/test_helpers.h
[Ticket](https://viam.atlassian.net/browse/RSDK-3541)
1. Change CartoFacade::GetPosition() to return the actual pose from cartographer, which is updated when CartoFacade::AddSensorReading is called.
2. Remove unused fields from viam_carto_get_position_response (those which are needed for the GetPositionResponse protobuf type but which are filled in using the go spatial math library, which is not available to the cartographer C++ code. 
3. Remove component_reference from the `viam_carto_config` C type. This was done b/c it was previously assumed to be equal to the first element of the sensors list without adding any additional information. Removing it make sit clear that the component_reference is assumed to be the first element of the sensors list (which is the behavior of …
> [RSDK-3541] CartoFacade GetPosition

- viam-cartographer/src/carto_facade/carto_facade_test.cc
- viam-cartographer/src/carto_facade/test_helpers.cc
I forgot to add a header include: https://github.com/viamrobotics/viam-cartographer/pull/160/files#diff-49d4a9777ef7773792665e3523fe1c5032de5373119d778dd3e461329a60399fR10 
This apparently is only caught by clang, which is only used on mac, which we don't test in CI.
Detected in this PR:
https://github.com/viamrobotics/viam-cartographer/pull/170/files#diff-49d4a9777ef7773792665e3523fe1c5032de5373119d778dd3e461329a60399fR4
This also changes the map_rate_sec from 1 to 60 to prevent flakey tests failures if it takes longer than a second to add all the lidar data which may cause add_lidar_reading to fail unexpectedly as the lock is held by the background thread which saves internal state to disk: https://github.com/viamrobotics/viam-cartographer/actions/runs/5414901563/jobs/9842617172?pr=179
> hotfix-fix-compile-error-on-mac

- cartofacade/capi.go
- cartofacade/carto_facade.go
- cartofacade/carto_facade_mock.go
- cartofacade/carto_facade_test.go
- internal/testhelper/testhelper.go
- sensorprocess/sensorprocess.go
- sensorprocess/sensorprocess_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-3545)
- `sensorprocess.Start` polls the lidar to get the next sensor reading and adds it to the mapBuilder by calling `addSensorReading` in a loop and exits if the context provided is canceled. 
- `addSensorReading` checks if the metadata from the GRPC call has a timestamp, if it does it calls `addSensorReadingFromReplaySensor` otherwise It calls `addSensorReadingFromLiveReadings`
- `addSensorReadingFromReplaySensor` continuously calls `cartofacade.AddSensorReading` until it succeeds 
- `addSensorReadingFromLiveReadings` calls cartofacade.AddSensorReading once and skips the reading if it does not succeed
- There is also a change to the testhelper file so that we can mock a replay sensor that returns a corrupted time stamp that would not be …
> [RSDK-3545] add sensor process

- viam-cartographer.go
- viam-cartographer_internal_test.go
[RSDK-3950](https://viam.atlassian.net/browse/RSDK-3950)
- If the modularizationV2Enabled feature flag is true, call into the new cartofacade API for getPosition
- Write unit tests to ensure new conversion returns the same values as the old conversions would have
[RSDK-3950]: https://viam.atlassian.net/browse/RSDK-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-3950 - call into cgo for getPosition

- viam-cartographer.go
- viam-cartographer_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-2854)
1. Protect close with a mutex (atomic)
2. Have close return early if already closed (idempotent)
3. Ensure methods which will be called by the slam GRPC server return & log errors if called after the resource is closed
> [RSDK-2854] make-close-atomic-and-idempotent

- viam-cartographer.go
adds a jobs done file when the replay camera stops. additionally prevents cartographer from repeating the warning about the job being completed.
Additional issue is this file gets created when all lidar scans are read into the job, but this does not mean that all lidar scans have been processed
unsure of interactions with full mod and interactions with a live replay camera
> add jobs done file

- viam-cartographer.go
- viam-cartographer_internal_test.go
- viam-cartographer_test.go
[RSDK-3695](https://viam.atlassian.net/browse/RSDK-3965)
- If the modularizationV2Enabled feature flag is true, call into the new cartofacade API for GetPointCloudMap
- Write unit tests to make sure cgo is returning the same output that the original code would have
[RSDK-3695]: https://viam.atlassian.net/browse/RSDK-3695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-3965 - call into cgo for getPointCloudMap

- viam-cartographer.go
- viam-cartographer_internal_test.go
- viam-cartographer_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-3992)
- If the modularizationV2Enabled feature flag is true, call into the new cartofacade API for GetInternalState
- Write unit tests to make sure cgo is returning the same output that the original code would have
> RSDK-3992 - call into cgo for GetInternalState

- viam-cartographer_test.go
- GetLatestMapInfo just returns a field on the Cartographer Service struct, so no changes are needed for full mod for this endpoint
- Add in the tests for GetLatestMapInfo to the tests where the feature flag is on to make sure it is still behaving as expected
> RSDK-4002 - add GetLatestMapInfo tests to full mod tests

- cartofacade/capi.go
- cartofacade/capi_test.go
- cartofacade/carto_facade.go
- cartofacade/carto_facade_mock.go
- cartofacade/carto_facade_test.go
- sensors/lidar/dim-2d/dim-2d_test.go
- viam-cartographer.go
- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade.h
- viam-cartographer/src/carto_facade/carto_facade_test.cc
[Ticket](https://viam.atlassian.net/browse/RSDK-3546)
[Ticket](https://viam.atlassian.net/browse/RSDK-2897)
[Ticket](https://viam.atlassian.net/browse/RSDK-2124)
[Ticket](https://viam.atlassian.net/browse/RSDK-1787)
1. Renames `ActionMode` to `SlamMode` in C++ code (to more closely reflect its intent of representing whether cartographer is running in Mapping, Updating, or Localizing mode).
2. Returns the SlamMode from viam_cartographer_init all the way back to the cartographer module
3. This information is needed in order to keep integration tests at parity with what they are now (prior to full mod the integration tests watched logs to determine what mode cartographer is in, now we can just have the C++ carto facade the go code what the slam mode is on initialization.
Pre work required …
> [RSDK-3546] report-slam-mode

- integration_test.go
- internal/testhelper/testhelper.go
- sensorprocess/sensorprocess.go
- sensors/lidar/dim-2d/dim-2d.go
- sensors/lidar/dim-2d/dim-2d_test.go
- sensors/lidar/lidar.go
- sensors/lidar/lidar_test.go
- sensors/sensor_mock.go
- sensors/sensors.go
- sensors/sensors_test.go
- testhelper/testhelper.go
- viam-cartographer.go
- viam-cartographer_internal_test.go
- viam-cartographer_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-3546)
[Ticket](https://viam.atlassian.net/browse/RSDK-2897)
[Ticket](https://viam.atlassian.net/browse/RSDK-2124)
[Ticket](https://viam.atlassian.net/browse/RSDK-1787)
1. Add integration tests for the carttesian product of `slam_mode = [mapping,updating,localizing]` and `sensor_type = [live, replay]` 
2. Have integration tests expect position outcomes in integration tests on mac & linux due to https://viam.atlassian.net/browse/RSDK-3866
3. Change viamcartographer.New to take an override TimedSensor, to allow integration tests to control the timestamps of lidar readings, and make integration tests deterministic
4. Add TimedSensor interface which wraps a lidar reading. Change all post full mode code to interact with lidars through that …
> [RSDK-3546] update-full-mod-integration-tests

- viam-cartographer/src/carto_facade/util.cc
This makes it so that the full mod PCD parser for Lidar readings only expects lidar readings to have XYZ rather than XYZRGB. This is needed as PCL will log errors for every lidar reading unless we either:
1. Parse the headers as RPlidar outputs them
2. Change RPlidar to output PCDs in the format this code expects
3. Suppress PCL errors
This code change does 1 for post full mod.
Pre full mod code does 3. 
This is the header that RPlidar outputs currently:
```
VERSION .7
FIELDS x y z
SIZE 4 4 4
TYPE F F F
COUNT 1 1 1
WIDTH 806
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 806
DATA binary
```
Without this change the following log is emitted by the PCL library:
`Failed to find match for field 'rgb`
Pre full mod suppressed this error using `pcl::console::setVerbosityLevel(pcl::console::L_ALWAYS);` …
> fix-pcd-parse-error-log

- Makefile
[Ticket](https://viam.atlassian.net/browse/RSDK-4039)
Fixes `make build` not rebuilding cartographer-module if it has been built before. 
Now `make build` always rebuilds the cartographer-module go binary.
Follows the same pattern as: viam-server's `make server` make target: https://github.com/viamrobotics/rdk/blob/main/Makefile#L81
I accidentally introduced this bug in the build system in https://github.com/viamrobotics/viam-cartographer/pull/186
> [RSDK-4039] fix-makefile-not-rebuilding

- cartofacade/capi.go
- cartofacade/capi_test.go
- integration_test.go
- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade.h
- viam-cartographer/src/carto_facade/carto_facade_test.cc
- viam-cartographer/src/carto_facade/util.cc
- viam-cartographer/src/carto_facade/util.h
- viam-cartographer/src/slam_service/slam_service.cc
During the [Full Mod Hardware Test](https://viam.atlassian.net/browse/RSDK-3548) we discovered that full mod wasn't creating maps correctly.
We root caused it & found that it was b/c the way we were describing the time of each lidar reading in full mod (prior to this PR) was:
```
point_cloud.time =
cartographer::common::FromUniversal(sensor_reading_time_unix_micro);
```
This PR changes it to:
```
point_cloud.time =
cartographer::common::FromUniversal(0) +
cartographer::common::FromMilliseconds(sensor_reading_time_unix_milli);
```
This bug was due to me misinterpreting `cartographer::common::FromUniversal` to be taking a unix timestamp in microseconds, but instead it appears to be taking `ticks` http://docs.ros.org/en/lunar/api/cartographer/html/namespacecartographer_1_1common.html which …
> fix-full-mod-cartographer-time

- sensorprocess/sensorprocess.go
- testhelper/testhelper.go
errors.Is is not working because the actual error is wrapped with other errors and the old tests still passed because the mock function returns exactly the error the code is checking. Updated to check the if the error message contains the string from rdk and so that the test returns a wrapped error
> RSDK-4074 - quick fix for logging

- .github/workflows/releasecandidate.yml
- .github/workflows/stable.yml
The github action to create the rc candidate failed because of this typo: https://github.com/viamrobotics/viam-cartographer/actions/runs/5618273249
> RSDK-4122 Fix typo in viam-cartographer github workflows

- etc/packaging/appimages/cartographer-module-aarch64.yml
- etc/packaging/appimages/cartographer-module-x86_64.yml
Adds nlopt to app image as it is now a hard RDK requirement to provide nlopt.
Fixes cartographer-module not booting on linux as the app image doesn't contain the nlopt dynamic lib which RDK requires:
```
robot_server.process.cartographer-module_./cartographer-module.StdErr pexec/managed_process.go:222 \_ /tmp/appimage_extracted_81e530268ca6420dff0edd4f4f8e5ec8/usr/bin/cartographer-module: error while loading shared libraries: libnlopt.so.0: cannot open shared object file: No such file or directory
```
Manual testing:
```
sudo curl -o /usr/local/bin/rplidar-module https://storage.googleapis.com/packages.viam.com/apps/rplidar/rplidar-module-stable-aarch64.AppImage
sudo curl -o /usr/local/bin/cartographer-module-latest https://storage.googleapis.com/packages.viam.com/apps/slam-servers/cartogr …
```
> hotfix-add-nlopt

- viam_cartographer.go
- viam_cartographer_test.go
Switch from updating timestamp in GetPointCloudMap to updating timestamp every time GetLatestMapInfo is called when not in localizing mode.
> RSDK-4193: New Logic for GetLatestMapInfo

- viam_cartographer_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-4259)
This is cleaning up test cases that were not consolidated properly during: https://github.com/viamrobotics/viam-cartographer/pull/207
> RSDK-4259-remove-feature-flag-language-from-tests

- cartofacade/capi.go
- cartofacade/capi_test.go
- cartofacade/carto_facade.go
- cartofacade/testhelpers.go
- config/config.go
- config/config_test.go
- integration_test.go
- sensorprocess/sensorprocess.go
- sensorprocess/sensorprocess_test.go
- sensors/sensors.go
- sensors/sensors_test.go
- sensors/test_deps.go
- testhelper/testhelper.go
- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade.h
- viam-cartographer/src/carto_facade/carto_facade_test.cc
- viam_cartographer.go
- viam_cartographer_internal_test.go
- viam_cartographer_test.go
- Edit lidar naming and config
- Build data frequency into lidar map rather than separate variable
- Add feature flag
Testing new config structure with replay sensor: 
```javascript
{
"components": [
{
"type": "camera",
"model": "replay_pcd",
"attributes": {
"time_interval": {
"end": "2023-07-31T18:31:30.597920Z",
"start": "2023-07-31T18:31:17.597920Z"
},
"batch_size": 50,
"robot_id": "d1f2018b-6de0-449f-8d7a-7e6fd8ace7b3",
"source": "MULAN"
},
"depends_on": [],
"name": "replay-camera"
}
],
"services": [
{
"type": "slam",
"model": "viam:slam:cartographer",
"attributes": {
"camera": {
"name": "replay-camera"
},
"config_params": {
"mode": "2d"
},
"data_dir": "/Users/patriciastrutz/Development/Data/new_new_data",
"imu_integration_enabled": true
},
"name": "slam"
}
],
"modules": [
{
"name": …
```
> [RSDK-4106] Restructure lidar name and data rate to use map

- config/config.go
- config/config_test.go
- viam_cartographer.go
- viam_cartographer_internal_test.go
* adds feature flag to put cloud story changes behind. Feature flag will be provided through the config as `cloud_story_enabled`
* adds config changes for `existing_map`, `enable_mapping`, and `run_slam`
* validates that `existing_map` has been provided
* adds parsing & tests for new config params
* does not create a new getOptionalParameters func
> RSDK-4345 - add feature flag for cloud story

- cartofacade/capi.go
- cartofacade/capi_test.go
- cartofacade/testhelpers.go
- config/config.go
- config/config_test.go
- sensorprocess/sensorprocess.go
- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade.h
- viam-cartographer/src/carto_facade/carto_facade_test.cc
- viam_cartographer.go
1.  **add `enable_mapping` to config. If `cloud_story_enabled` == true: use `enable_mapping=false` in place of `map_rate_sec = 0` to determine if we are in `LOCALIZING` mode or not**
2. if cloud story is enabled, do not validate `map_rate_sec`. Remove logic to save internal state to the `data_dir`
3. If cloud story is enabled stop validating `data_dir`, add `existing_map` to optional parameters. Use `existing_state` to get any existing map 
**This PR implements number 1**
* remove config validatation for `cloud_story_enabled`
* pass `cloud_story_enabled` feature flag all the way to C++ code
* add `enable_mapping` to config & pass it all the way down to C++ code
* 
* remove old testing logic associated with incorrect validations
* add in new config params to test
> RSDK-4361 - add enable mapping flag for cloud story

- cartofacade/capi.go
- cartofacade/capi_mock.go
- cartofacade/capi_test.go
- cartofacade/carto_facade.go
- cartofacade/carto_facade_mock.go
- cartofacade/carto_facade_test.go
- sensorprocess/sensorprocess.go
- sensorprocess/sensorprocess_test.go
- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade.h
- viam-cartographer/src/carto_facade/carto_facade_test.cc
- viam-cartographer/src/carto_facade/util.cc
- viam-cartographer/src/carto_facade/util.h
- viam-cartographer/src/carto_facade/util_test.cc
Rename functions currently using 'sensor' to denote lidar to explicitly use 'lidar', to be able to better distinguish between lidar and IMU
> [RSDK-4487] Rename lidar functions

- cartofacade/capi.go
- cartofacade/capi_mock.go
- cartofacade/carto_facade_test.go
- sensorprocess/sensorprocess_test.go
Improved readability by changing tests from looking like this:
```bash
=== RUN   TestRequest
=== RUN   TestRequest/test_successful_request
=== RUN   TestRequest/test_failed_request
=== RUN   TestRequest/test_requesting_with_a_canceled_context
=== RUN   TestRequest/test_requesting_with_when_the_work_function_takes_longer_than_the_timeout
--- PASS: TestRequest (0.05s)
--- PASS: TestRequest/test_successful_request (0.00s)
--- PASS: TestRequest/test_failed_request (0.00s)
--- PASS: TestRequest/test_requesting_with_a_canceled_context (0.00s)
--- PASS: TestRequest/test_requesting_with_when_the_work_function_takes_longer_than_the_timeout (0.05s)
=== RUN   TestStart
=== RUN   TestStart/testing_Start
--- PASS: TestStart (0.05s)
--- PASS: TestStart/testing_Start (0.00s)
=== RUN   TestStop
=== RUN …
```
> Minor fixes & refactor

- sensors/sensors.go
Updates cartographer to pass validation if a replay camera is waiting for data
> [RSDK-3906] validation passes when a replay camera does not have data present

- viam_cartographer.go
Hey yall, this PR is to remove the unused DefaultExecutableName as it is no longer used.
**Testing:**
None outside of CI tests
> RSDK-4936 Remove DefaultExecutableName

- sensors/sensors.go
- viam_cartographer.go
Hey yall, this PR is to remove logging about a missing movement sensor if it is not configured as it is not actually an error to surface to the user. 
I also changed one log from a warning to debug for the same reasons. 
**Testing:**
Ran `viam-cartographer` locally after changes to make sure no warning logs showed up.
> RSDK-4933 Remove logging for IMU if not configured

- viam_cartographer.go
adjusts the code to run sensor validation on the source robot when using cloudslam. If validation fails, the slam card will not appear & the user will see logs pertaining to the failure
https://viam.atlassian.net/browse/RSDK-5601
> [RSDK-5601] Add sensor validation when using cloudslam

- .canon.yaml
- .github/workflows/appimage.yml
- .github/workflows/bump_dependencies.yml
- .github/workflows/deploy_module.yml
- .github/workflows/test.yml
- etc/canon-update.sh
- etc/packaging/appimages/cartographer-module-aarch64.yml
- etc/packaging/appimages/cartographer-module-x86_64.yml
Tested arm64 appiamge on bookworm pi
> Reduce Appimage Size

- sensorprocess/lidarsensorprocess.go
- sensorprocess/movementsensorprocess.go
- sensorprocess/sensorprocess.go
https://viam.atlassian.net/browse/RSDK-5560
testing for adjusting the online replay sensor process to reduce the lag buildup in cloudslam. User's will see changes in their map within 5-10 seconds, and can be configured to be shorter by adjusting the sync rate in the user's capture config.
> [RSDK-5560] tweak replay sensor process

- config/config.go
- sensorprocess/lidarsensorprocess_test.go
- sensorprocess/movementsensorprocess.go
- sensorprocess/movementsensorprocess_test.go
- sensorprocess/sensorprocess.go
- sensorprocess/sensorprocess_test.go
- sensorprocess/testhelper.go
- sensors/movementsensor.go
- sensors/movementsensor_test.go
- sensors/test_deps.go
- testhelper/integrationtesthelper.go
- viam_cartographer.go
Ticket: https://viam.atlassian.net/browse/RSDK-4862
**Tested on:**
* Intel Mac w/ lidar
* Cloud slam (live mode) results show an overall improvement in mapping quality based on this PR. They also show a similar map quality for both IMU and IMU + odometer mapping, though the latter leads to higher confidence sooner than just using an IMU. I could not test mapping using just an odometer because cloud slam won't start unless the data manager is capturing IMU data.
**Cloud slam - live mode:**
NOTE: Unbeknownst to me, the IMU was providing only zero values. The map quality in the results below is therefore not representative of what the actual performance likely looks like. But the maps do still serve as a proof that adding IMU and odometer data is successful.
| | main branch - w/ imu  | this …
> RSDK-4862 - Add odometer sensor process

- viam-cartographer/src/carto_facade/carto_facade.cc
- viam-cartographer/src/carto_facade/carto_facade_test.cc
This PR converts the cartographer logs to info instead of err.
------------------------------------------------------- BEFORE --------------------------------------------------------
Run with: **go run web/cmd/server/main.go -config /etc/viam.json -debug**
```
2024-01-29T13:21:21.302-0500	ERROR	robot_server	zap/options.go:212	finished unary call with code Unknown	{"grpc.start_time": "2024-01-29T13:21:21-05:00", "system": "grpc", "span.kind": "server", "grpc.service": "viam.service.motion.v1.MotionService", "grpc.method": "GetPlan", "error": "rpc error: code = Unknown desc = resource \"rdk:component:base/viam_base\" not found", "grpc.code": "Unknown", "grpc.time_ms": 0.456}
2024-01-29T13:21:26.416-0500	ERROR	robot_server	zap/options.go:212	finished unary call with code Unknown …
```
> RSDK-1888 Change log level for cartographer logs

- viam_cartographer.go
https://viam.atlassian.net/browse/RSDK-5663
in an attempt to help cloudslam with larger maps, we are increasing the timeouts for PointCloudMap and InternalState. this will hopefully allow plenty of time for cloudslam to get the internal state. this fix is not guaranteed to work for all large maps
> [RSDK-5663] increase internal state and pointcloud timeouts

- viam_cartographer.go
- viam_cartographer_test.go
quick pr to let properties be called while cloudslam is configured
> unblock properties

- viam_cartographer.go
- viam_cartographer_internal_test.go
lets the strings not fail if empty strings are passed in for min and max range, and fixes properties while cloudslam is enabled
https://viam.atlassian.net/browse/RSDK-7269
> [RSDK-7269] allow for empty config params and fix properties

- config/config.go
- config/config_test.go
- viam_cartographer.go
- viam_cartographer_test.go
https://viam.atlassian.net/browse/RSDK-7214
> [RSDK-7214] set default mode
