Makefile
Ticket: https://viam.atlassian.net/browse/RSDK-2102
Mirror of: https://github.com/viamrobotics/viam-orb-slam3/pull/9
=> RSDK-2102 Ensure cartographer submodule is initialized

viam-cartographer/src/slam_service/slam_service.cc, viam-cartographer/src/slam_service/slam_service.h
Reverts viamrobotics/viam-cartographer#10
=> Revert "[RSDK-2214] remove old api endpoints"

README.md
Ticket: https://viam.atlassian.net/browse/RSDK-2875
Done:
* Updated README to reflect the changes made during modularization
View the updated README here: https://github.com/kkufieta/viam-cartographer/blob/kk/rsdk-2875-update-readme-makefile/README.md
=> RSDK-2875 - Update README to work for modules

Makefile, viam-cartographer/scripts/setup_cartographer_linux.sh, viam-cartographer/scripts/setup_cartographer_macos.sh
[Ticket](https://viam.atlassian.net/browse/RSDK-3604)
This is work required to unblock: https://github.com/viamrobotics/viam-cartographer/pull/127/files
=> RSDK-3604-install-artifact

Makefile, etc/packaging/appimages/cartographer-module-aarch64.yml, etc/packaging/appimages/cartographer-module-x86_64.yml, viam-cartographer/lua_files/map_builder.lua, viam-cartographer/lua_files/map_builder_server.lua, viam-cartographer/lua_files/pose_graph.lua, viam-cartographer/lua_files/trajectory_builder.lua, viam-cartographer/lua_files/trajectory_builder_2d.lua, viam-cartographer/lua_files/trajectory_builder_3d.lua
[Ticket](https://viam.atlassian.net/browse/RSDK-3603)
This is work required to unblock: https://github.com/viamrobotics/viam-cartographer/pull/127/files
Manually tested on both a PI appimage & aarm64 osx
=> RSDK-3603-consolidate-lua-files

.github/workflows/main.yml
Follow up from https://github.com/viamrobotics/viam-cartographer/pull/144
=> hotfix-point-workflow-back-at-main

Makefile
Reverts viamrobotics/viam-cartographer#158
Need to revert as the CMAKE change it is built upon causes: https://viam.atlassian.net/browse/RSDK-3785
=> Revert "update-makefile-dont-buf-every-time"

.github/workflows/appimage-comment.yml, etc/packaging/appimages/cartographer-module-aarch64.yml, etc/packaging/appimages/cartographer-module-x86_64.yml
This hopefully fixes the specific missing package errors in https://viam.atlassian.net/browse/RSDK-3785
=> RSDK-3785 Add new deps to AppImage recipes

Makefile
Reverts viamrobotics/viam-cartographer#162
=> Revert "Revert "update-makefile-dont-buf-every-time""

module/main.go
This PR adds debug logging viam-cartographer module based on the log level of the viam-server. 
Note: additional work will need to be done in full mod to apply this log level to the c++ code
JIRA Ticket: https://viam.atlassian.net/browse/RSDK-3809
=> RSDK-3809 Add Debug Logging

.github/workflows/test.yml, Makefile
[Ticket](https://viam.atlassian.net/browse/RSDK-4148)
=> [RSDK-4148] remove-makefile-and-gh-action-full-mod

.github/workflows/test.yml, Makefile
Reverts viamrobotics/viam-cartographer#216
=> Revert "[RSDK-4148] remove-makefile-and-gh-action-full-mod"

.artifact/tree.json, integration_test.go, testhelper/testhelper.go
update mock lidar artifact dataset to reflect data format that we use in the code
=> RSDK-4064 - update mock lidar artifact dataset

.github/workflows/test.yml, Makefile
[Ticket](https://viam.atlassian.net/browse/RSDK-4148)
Reverts viamrobotics/viam-cartographer#220
Will require force merging
=> Revert "Revert "[RSDK-4148] remove-makefile-and-gh-action-full-mod""

.github/workflows/test.yml, Makefile
Reverts viamrobotics/viam-cartographer#221
=> Revert "Revert "Revert "[RSDK-4148] remove-makefile-and-gh-action-full-mod"""

.github/workflows/test.yml, Makefile
[Ticket](https://viam.atlassian.net/browse/RSDK-4240)
[Ticket](https://viam.atlassian.net/browse/RSDK-4148)
Will require a force merge.
I've tested each step of test.yml in canon on my mac & they all pass.
=> RSDK-4148-fix-post-full-mod-ci

cartofacade/capi.go, cartofacade/capi_test.go, cartofacade/carto_facade_test.go, cartofacade/testhelpers.go, config/config.go, config/config_test.go, viam-cartographer/src/carto_facade/carto_facade.cc, viam-cartographer/src/carto_facade/carto_facade.h, viam-cartographer/src/carto_facade/carto_facade_test.cc, viam_cartographer.go
- Add IMU config parameters in Go code.
- Add IMU into cartographer struct and cartofacade config
- Add IMU as an optional parameter in GetOptionalParameters
- Add tests for IMU config
=> [RSDK-4137] Config changes for IMU Support

config/config.go, integration_test.go, sensorprocess/sensorprocess.go, sensorprocess/sensorprocess_test.go, sensors/sensor_mock.go, sensors/sensors.go, sensors/sensors_test.go, sensors/test_deps.go, testhelper/testhelper.go, viam_cartographer.go, viam_cartographer_internal_test.go, viam_cartographer_test.go
- Implement functions to create new IMU and retrieve IMU Data
- Add TimedIMUSensor for storing IMU data with timestamp
- Add IMU to cartographer service
- Create dependencies for test IMUs
=> [RSDK-4108] Sensor Process for IMU Data

viam-cartographer/src/carto_facade/carto_facade.cc
Write internal state to temp directory that exists when cloud story is enabled
=> RSDK-4572 - data_dir to existing_map config change bug fix

config/config.go, config/config_test.go
* throw an error if config suggests `localization mode` & `offline mode`
* update tests to test above change
=> RSDK-2262 - use config to determine slam mode during validation

integration_test.go, testhelper/testhelper.go
=> [RSDK-4448] Flaky test - TestCartographerIntegration2D

.github/workflows/deploy_module.yml, meta.json
This PR includes the meta.json and deploy_module.yml workflow needed to add Cartographer to the Viam registry. Second PR may be coming soon with minor edits
=> Add Cartographer to Viam Registry - Initial Deployment

.github/workflows/appimage.yml, .github/workflows/deploy_module.yml, .github/workflows/test.yml
qemu-host is currently down so James has instructed us to move to a linux self-hosted until we can do a full switch to buildjet
=> Hotfix - Switch github runners

module/sample_linux.json, module/sample_osx.json
Hey yall, this PR is to update the sample configs in cartographer with the new cloud story and IMU changes.
=> RSDK-5386 Update cartographer configs with cloud slam

cartofacade/carto_facade_mock.go, integration_test.go, sensorprocess/lidarsensorprocess.go, sensorprocess/movementsensorprocess.go, sensorprocess/sensorprocess.go, sensorprocess/sensorprocess_test.go, sensorprocess/testhelper.go, sensors/lidar.go, sensors/lidar_test.go, sensors/movementsensor.go, sensors/movementsensor_test.go, testhelper/integrationtesthelper.go, viam_cartographer.go
This refactor serves the purpose of simplifying implementing & reviewing:
* C++/cgo support for Odometer: https://viam.atlassian.net/browse/RSDK-4861
* Sensorprocess for Odometer: https://viam.atlassian.net/browse/RSDK-4862
**Done:**
* Move test helpers from main test files into already existing testhelper files.
* Fix bug in integration tests: We ran everything in offline mode. It runs as expected now. The expected values had to be updated as a result of that.
* Fix offline mode.
* Rewrite offline mode to make it deterministically sequential.
* Add & remove tests based on the changed offline mode.
**Tested online mode on RPI:**
Ensured that online mode still works on the RPI.
**Tested on Intel Mac on the same dataset:** 
This PR fixes the currently broken offline mode on the main branch. …
=> Refactor: Sequentialize offline mode

postprocess/postprocess.go, postprocess/postprocess_test.go
add Red to postprocessed points so we can make them a different color on the FE
=> RSDK - 6222 - make postprocessed points red

postprocess/postprocess.go, viam_cartographer.go, viam_cartographer_test.go
This PR updates cartographer to be able to read in a postprocessed pcd and return that form PointCloudMap instead of calculating it each timte.
=> RSDK-6244 - read from pcd

sensorprocess/lidarsensorprocess.go, sensorprocess/movementsensorprocess.go
=> Fix comments

integration_test.go, testhelper/integrationtesthelper.go
Refactoring the integration tests for ticket: https://viam.atlassian.net/browse/RSDK-4863
=> Refactor integration tests

.artifact/tree.json, integration_test.go, testhelper/integrationtesthelper.go
Tickets:
* https://viam.atlassian.net/browse/RSDK-4863
* https://viam.atlassian.net/browse/RSDK-4670
Done:
* Added new data for integration tests using odometry data
* Extended tests to test lidar and odometry data
* Improved logging
=> RSDK-4863 & RSDK-4670 - Integration tests for odometry & logging improvements
